platform :ios, '9.0'

target 'task-05p' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for task-05p
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'AlamofireImage'

  target 'task-05pTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'task-05pUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
